name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
      
    - name: Build iOS target
      run: xcodebuild build -scheme MYImageCropper
      
    - name: Run iOS tests
      run: xcodebuild test -scheme MYImageCropper
