name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build for iOS
      run: xcodebuild build -scheme MYImageCropper -destination "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest"
      
    - name: Test for iOS
      run: xcodebuild test -scheme MYImageCropper -destination "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest"
